languague: python
python:
    - 3.5
    - 2.7
env:
  COMPOSE_VERSION=1.8.1
before_install:
- sudo apt-get update
- wget -qO- https://get.docker.com/ | sh
- sudo usermod -a -G docker `whoami`
- sudo wget https://github.com/docker/compose/releases/download/$COMPOSE_VERSION/docker-compose-`uname -s`-`uname -m` -O /usr/local/bin/docker-compose
- sudo chmod +x /usr/local/bin/docker-compose
- curl https://bootstrap.pypa.io/get-pip.py | sudo python3
install:
- sudo pip3 install flake8
script:
    flake8 --config=.flake8
notifications:
  email:
    recipients:
      - khainguyen@onfta.com
    on_success: change
on_failure: always
